# Setup
title: Two Line Project
email: twolineproject@protonmail.com
description: >-
  Two Line Project
baseurl: ""
url: "https://twolineproject.github.io"
github_username: twolineproject

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
sass:
  sass_dir: css
  style: compressed

exclude:
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
